### ISSUE TITLE
Grouping styles

### ISSUE THREAD

**Issue by DeNelo** [tmont/sunlight#13]
Hi,
I wish the `.sunlight*` styles were all called `pre.sunlight*`
In my authoring tool I have a list of styles that appear where they are allowed. This means that all styles in the imported `sunlight.default.css` file appear at the top of the list.
I tried renaming the styles to `pre.sunlight*` - that would be really nice, because then all the styles were grouped below `pre`, and I could even hide them.
But if I rename the styles, the javascript does not work correctly - the color coding is gone.
I know this is just a convenience issue... but it is quite annoying having to scroll through the full list (almost full, as I've removed the styles that do not apply to my programming language) every time you need some style.
Apart from this - thanks for a great tool!
-Niels

**Comment by tmont** [comment]
I'm not sure I really follow what you're asking. Do you want the class names to be named something different, i.e. with a different prefix? There is an option for that (make sure to change your CSS, though): http://sunlightjs.com/docs.html#class-prefix

If you're referring to something else, can you be more specific or provide some sample CSS/HTML of what you're after?

**Comment by DeNelo** [comment]
Hi,
Sorry for the LATE reply. You got me in the right direction, thanks!
