### ISSUE TITLE
Symbols in Scala break scoping 

### ISSUE THREAD

**Issue by alvaroc1** [tmont/sunlight#3]
val x = 'aSymbolLiteral

I think this is a common issue on all syntax highlighters. Sunlight treats it as a scoping symbol (rightly so for character types), but that's wrong for symbol literals.

**Comment by tmont** [comment]
@alvaroc1

Thanks, I didn't know about those.

I got symbol literals implemented, but I'm not a Scala person at all, so can you tell me what you would expect the following to highlight as?

``` scala
val foo = 'asdf '
```

Would you expect a `char` with value `'asdf '`, or would it be a symbol with value `'asdf` and a syntax error with an unclosed single quote?

**Comment by alvaroc1** [comment]
It would be the second: symbol and syntax error. A char can only be one
character.

**Comment by tmont** [comment]
Symbol literals should now be supported in 1.20.0.

You can download from the main site: http://sunlightjs.com/#download

Or from the tag: https://github.com/tmont/sunlight/releases/tag/1.20.0

**Comment by alvaroc1** [comment]
Wow. That was fast. Thanks! And thanks for this awesome tool.

**Comment by tmont** [comment]
No probalo.
