### ISSUE TITLE
xml highlighting - dots in tag names

### ISSUE THREAD

**Issue by cadilhac** [tmont/sunlight#5]
Hi,

I was trying to highlight a web.config file from asp.net MVC. Tags have dots:
ex:

``` xml
<system.net>
```

When highlighted, "system." is blue and "net" is red. It should be one color only, as github is doing on the above code block.

Thanks

**Comment by tmont** [comment]
Fixed in v1.21.0. You can download it from http://sunlightjs.com/#download or get the source code from the tag: https://github.com/tmont/sunlight/releases/tag/1.21.0

Demo here: http://sunlightjs.com/demo.html#xml

**Comment by cadilhac** [comment]
Thanks a lot.
