### ISSUE TITLE
Line numbering not working

### ISSUE THREAD

**Issue by MihalisL** [tmont/sunlight#6]
Hi,

while syntax highlighting works for objective-c code, I get the following error when enabling line numbering options for highlighting:

![screen shot 2014-01-05 at 16 25 18](https://f.cloud.github.com/assets/660029/1846734/44496722-7615-11e3-94bf-3cf31de575f3.png)

The error was logged with Firebug on Firefox.

After this syntax highlighting for subsequent blocks of code fails completely, i.e. no highlighting at all. 

My code within the document ready handler is:

```
var highlightOptions = {lineNumbers:true, lineNumberStart:0};
var highlighter = new Sunlight.Highlighter(highlightOptions);

$('pre code').each(function() {
  $(this).addClass("sunlight-highlight-objective-c");
  highlighter.highlightNode(this);
});
```

which works fine if the highlightOptions is empty or even contains another setting for say, showWhitespace.

Thanks in advance,

Mike

**Comment by tmont** [comment]
Can you give me an example of the code you're trying to highlight, as well as the markup on the page?

Also, the line numbers are inserted automatically for block-level elements, so you shouldn't have to specify that option explicitly. What happens if you don't pass anything to the constructor?

**Comment by MihalisL** [comment]
Thanks for your reply.

I am using markdown for the page. Some text and code goes like:

A faster way would be to pop back to a view controller for which the index in the navigation stack is known beforehand. In that case, to go to the n-th view controller from the top of the stack, with the zero-indexed controller being the _topViewController_, we could write:

```
- (void)popToViewControllerWithIndexFromTop:(NSUInteger)index
        animated:(BOOL)animated{
    NSUInteger startIndex = (self.viewControllers.count - 1) - index;
    UIViewController *selectedController = [self.viewControllers 
        objectAtIndex:startIndex];
    [self popToViewController:selectedController animated:animated];
}
```

which renders like this:

![screen shot 2014-01-05 at 20 43 39](https://f.cloud.github.com/assets/660029/1847175/58d2feb4-7639-11e3-88a9-177e2cc74c11.png)

The above is what I exactly get if I do not pass anything to the constructor.

I am using nesta-cms (ruby based) which uses markdown for the article pages.

**Comment by tmont** [comment]
Can you view source and paste in the HTML? I'd like to be able to reproduce it.

By default, line numbers are only added to block-level elements (e.g. `<div>`), and it looks like you're trying to highlight an inline element because your `<code>` tag is nested in a `<pre>`. You could try adding a CSS rule to make the `<code>` elements block-level and see if that works.

Something like this:

``` javascript
$('pre code').each(function() {
  $(this).css('display', 'block').addClass('sunlight-highlight-objective-c');
  highlighter.highlightNode(this);
});
```

**Comment by MihalisL** [comment]
I have just added the css you have suggested, and line numbers have appeared! Thanks. The `<code>` within the `<pre>` elements are generated by markdown, so I went with the flow I guess.

![screen shot 2014-01-05 at 22 54 24](https://f.cloud.github.com/assets/660029/1847431/9f8124be-764b-11e3-83c8-e61258b619f6.png)

I would like to make the border around the block go away though. I have added this:

```
$(this).css({'display':'block', 'border':'none'}).addClass("sunlight-highlight-objective-c");
```

but it does not remove the border. I am not exactly a jQuery veteran :(

I will send you the page source by email.

Thanks again. 

Mike

**Comment by MihalisL** [comment]
Mike

**Comment by tmont** [comment]
Well, the border's not meant to be configurable, so it's a little wonky to modify it, unfortunately.

Probably the easiest way is to manually remove them after highlighting. The following should work:

``` javascript
$('.sunlight-code-container').css('border', 'none');
```

**Comment by MihalisL** [comment]
Thanks, I tried sending you the source, but I guess attachments do not show up here.

Since the article has not yet been published, could you give me an email address to post it to? Alternatively I will edit the text with Lorem Ipsums...

**Comment by MihalisL** [comment]
Here is a chunk of the article page source:

``` html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <title>My title</title>
    <!--[if ! lte IE 6]><!-->
    <link href='http://localhost:9393/css/master.css' media='screen' rel='stylesheet'>
    <!--<![endif]-->
    <!--[if lte IE 6]>
      <link href='http://universal-ie6-css.googlecode.com/files/ie6.1.1.css' media='screen, projection' rel='stylesheet'>
    <![endif]-->
    <!--[if lt IE 9]>
      <script src='//html5shim.googlecode.com/svn/trunk/html5.js'></script>
    <![endif]-->
    <link href='http://localhost:9393/articles.xml' rel='alternate' type='application/atom+xml'>

  </head>
  <body>
    <div id='container'>
      <header role='banner'>
          <hgroup>
            <h1>Heading 1</h1>
            <h2>Heading 2</h2>
          </hgroup>
        </header>
      <br>
<img src='/attachments/img.jpg' style='display: block; margin-left: auto; margin-right: auto; position: relative; right: 170px'>
<nav class='breadcrumb'>
  <ul>
    <li>
      <a href='http://localhost:9393/'>Home</a>
    </li>
    <li>
      Article title
    </li>
  </ul>
</nav>
<div id='content'>
  <article role='main'>
    <h1>Another title</h1>

<p><link rel="stylesheet" type="text/css" href="/attachments/javascript/scripts/sunlight-1.21.0/themes/sunlight.default.css" /></p>

<script src="/attachments/javascript/scripts/sunlight-1.21.0/sunlight-min.js"></script>

<script src="/attachments/javascript/scripts/sunlight-1.21.0/lang/sunlight.objective-c-min.js"></script>


<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>




<script>

$(document).ready(function() {

  var highlightOptions = {};//{showWhitespace:true, lineHighlight: [2, 4, 5, 6],lineNumbers:true};//, lineNumberStart:0};
  var highlighter = new Sunlight.Highlighter();

  $('pre code').each(function() {
      $(this).css({'display':'block', 'border':'none'}).addClass("sunlight-highlight-objective-c");
      highlighter.highlightNode(this);
  });

});
</script>


<p>Most of the time in an app there is the need to navigate back to the screen you were previously browsing. This is dead easy to do by calling:</p>

<blockquote><p>popViewControllerAnimated:(BOOL)animated</p></blockquote>

<p>on the <em>navigationController</em> member of the current view controller.</p>

<p>The above could be wrapped up in a method like so:</p>

<blockquote><p>-(void)popToViewControllerOfType:(Class)viewControllerClass animated:(BOOL)animated</p></blockquote>

<p>It would be nice to have access to the aforementioned functionality through <em>UINavigationController</em>. Since this is not the case by default, we could extend <em>UINavigationController</em> in a category:</p>

<pre><code>//  UINavigationController+PopToController.h&#x000A;#import &lt;UIKit/UIKit.h&gt;&#x000A;&#x000A;@interface UINavigationController (PopToController)&#x000A;&#x000A;- (void)popToViewControllerWithIndexFromTop:(NSUInteger)index&#x000A;    animated:(BOOL)animated;&#x000A;- (void)popToViewControllerOfType:(Class)viewControllerClass &#x000A;    animated:(BOOL)animated;&#x000A;@end&#x000A;</code></pre>
    <section class='pages'>

    </section>
    <footer>
      <p class='meta'>
        Published
        on
        <time datetime='2013-12-20T00:00:00+00:00' pubdate>20 December 2013</time>
      </p>
    </footer>
  </article>

</div>
<div id='sidebar'>
  <nav class='categories'>
  <h1>Articles by category</h1>
  <ul class='menu'>
    <li>
      <a href='http://localhost:9393/'></a>
    </li>
    <li class='current'>
      <a href='http://localhost:9393/objective-C/article-link'>article title</a>
    </li>
  </ul>
</nav>
  <div class='feed'>
    <a href='http://localhost:9393/articles.xml' title='Atom feed'>Atom feed</a>
  </div>
</div>
      <footer class='branding'>
          <p>
            Powered by Nesta, a
            <a href='http://nestacms.com'>Ruby CMS</a>.
          </p>
        </footer>
    </div>
  </body>
</html>
```
